### PR TITLE
Nvidia hardware cursors patch

### PR DESCRIPTION
**Pull request by Agent00Ming**
Commits taken from upstream [merge request](https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4596).
Works as expected from testing according to a handful of users, myself included.

### CODE REVIEW

**Comment by vaxerski** [comment]
question is whether we want to do this, as in, take wip mrs and merge them

**Comment by vaxerski** [comment]
I thought a bit about this - and for MRs that are WIP, it'd be a pain to rewrite history every time there is a change to them.

I have a better idea:
For WIP wlroots features we want to have:
- make a `patches/` directory
- put the MR as a patch there
- make meson run all patches in the directory before compiling

but I'll need to ask @fufexan regarding meson and patching, as I know very little meson. Fuf, does this sound reasonably doable?

**Comment by fufexan** [comment]
From what I could find, it might be feasible with https://mesonbuild.com/Wrap-dependency-system-manual.html#diff-files. Otherwise we can simply `run_command('git', 'apply', '-p1', '<patches>')`.

**Comment by vaxerski** [comment]
cool. Could you add the infra? Once that's done we can convert this MR into a new patch.

bascially apply all patches in `patches/`, you can add some dummy readme patch as a test

**Comment by Agent00Ming** [comment]
Should this be done with meson.build or passed as a PATCH_COMMAND over on the Hyprland CMakelist?

**Comment by vaxerski** [comment]
it's unrelated to hyprland, this would be a patch to wlroots.

**Review by vaxerski — APPROVED** [review]
let's fucking roll

**Pull request merged**
